name = "RadiationDetectorDSP"
uuid = "afd6e06f-c550-5763-af36-7391d39e46ec"
version = "0.2.2"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
CompositionsBase = "a33af91c-f02d-484b-be07-31d278c5ca2b"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
FunctionChains = "8e6b2b91-af83-483e-ba35-d00930e4cf9b"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
RadiationDetectorSignals = "bf2c0563-65cf-5db2-a620-ceb7de82658c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Adapt = "1, 2, 3"
ArgCheck = "1, 2"
ArraysOfArrays = "0.4, 0.5, 0.6"
CUDA = "3, 4, 5"
ChainRulesCore = "1"
CompositionsBase = "0.1"
DSP = "0.6, 0.7"
DocStringExtensions = "0.8, 0.9"
ElasticArrays = "1"
FFTW = "1"
FillArrays = "0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 1"
FunctionChains = "0.1"
GPUArraysCore = "0.1"
IntervalSets = "0.7"
InverseFunctions = "0.1"
JLArrays = "0.1"
KernelAbstractions = "0.8, 0.9"
Parameters = "0.12"
RadiationDetectorSignals = "0.3.3"
Requires = "1"
SIMD = "2,3"
StatsBase = "0.32, 0.33, 0.34"
StructArrays = "0.6"
TypedTables = "1.2"
UnPack = "1"
Unitful = "1"
julia = "1.6"

[extensions]
RadiationDetectorDSPCUDAExt = "CUDA"
RadiationDetectorDSPJLArraysExt = "JLArrays"

[extras]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
